name: Prod Release It

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - id: set-release-it-config
        run: |
          JSON=$(cat ./your.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"
      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2
          json-opts: ${{fromJson(./release-it.json)}}