name: Stage Release It

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Creating secrets files
        uses: './.github/actions/create-secrets-files'
        with:
          sentry-cli-rc: ${{ secrets.SENTRY_CLI_RC }}
      - run: npm install
      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2