name: Stage Release It

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2
          json-opts: >
            {
              "hooks": {
                  'after:bump': ['npx auto-changelog -p'],
                },
              "git": {
                "commit": "true",
                "commitMessage": "chore(release): ${version}",
                "tag": true,
                "tagName": "v${version}",
                "tagAnnotation": "v${version}"",
                "requireCommits": true,
                "changelog": 'npx auto-changelog --stdout --commit-limit false -u --template ./changelog.hbs',
              },
              "github": {
                "release": true,
                "releaseName": "v${version}",
                "assets": ["dist/*.zip"],
              },
              "npm": {
                "publish": false,
              }
            }