name: Prod Release It

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - name: release-it
        uses: TheRealWaldo/release-it@v0.7.2
        with:
          json-opts: >
            {
              "github": { "release": true },
              "git": { "tag": true, "commit": true },
              "plugins": {
                "@release-it/auto-changelog"
              }
            }
